processos = [
  {
    autor:"1Eduardo Lago Nunes", 
    reu: "Oi telefonia móvel",
    numeroProcesso: "00032535-23.2020.8.05.0001",
    vara: "15ª VS JE do consumidor",
    juiz: "Rosalvo Augusto",
    comarca: "Salvador Bahia",
    dataEntrada: "01/08/2020",
    atualizado: "25/12/2023",
    info: "Processo finalizado, transitado em julgado, habilitado na recuperação judicial. Acompanhando.",
  },
  {
    autor:"2Daniela Lago Nunes", 
    reu: "Oi telefonia móvel",
    numeroProcesso: "00032535-23.2020.8.05.0001",
    vara: "15ª VS JE do consumidor",
    juiz: "Rosalvo Augusto",
    comarca: "Salvador Bahia",
    dataEntrada: "01/08/2020",
    atualizado: "25/12/2023",
    info: "Processo finalizado, transitado em julgado, habilitado na recuperação judicial. Acompanhando.",
  },
  {
    autor:"3Debora Lago Nunes", 
    reu: "Oi telefonia móvel",
    numeroProcesso: "00032535-23.2020.8.05.0001",
    vara: "15ª VS JE do consumidor",
    juiz: "Rosalvo Augusto",
    comarca: "Salvador Bahia",
    dataEntrada: "01/08/2020",
    atualizado: "25/12/2023",
    info: "Processo finalizado, transitado em julgado, habilitado na recuperação judicial. Acompanhando. Processo finalizado, transitado em julgado, habilitado na recuperação judicial. Acompanhando. Processo finalizado, transitado em julgado, habilitado na recuperação judicial. Acompanhando.",
  },
];
module.exports = { processos };
